repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      name: black (cy/cyi/cyx/py/pyi/pyx)
      args: ["--line-length","88"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        args: ["--fix"]