name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pdm install 

    - name: Set git configs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Publish Release
      run: pdm run semantic-release publish -v DEBUG
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_USERNAME: ${{ secrets.PYPI_USERNAME }}
        REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    - name: Publish Changelog 
      run: |
        git add -u 
        git commit -m "[CI] BUMP VERSION and COMMIT CHANGELOG"