name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.11  # Version range or exact version of a Python version to use, the same as actions/setup-python
    - name: Install dependencies
      run: pdm install       # Then you can use pdm in the following steps.

    - name: Set git configs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    - name: Publish
      run: pdm run semantic-release publish -v DEBUG
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_USERNAME: __token__ # for PYPI
        REPOSITORY_PASSWORD: ${{ secrets.PYPY_TOKEN }}
        
